### ISSUE TITLE
Do you have any idea to how to commit this change on the actual branch

### ISSUE THREAD

**Issue by jsdaniell** [damienaicheh/update-android-version-gradle-action#1]

**Comment by damienaicheh** [comment]
Maybe try a git push using a simple shell command

**Comment by jsdaniell** [comment]
Alright, the solution code, can be useful for you sometime:

```yml
      - name: Update gradle version for Android
        uses: damienaicheh/update-android-version-gradle-action@v1.0.0
        with:
          build-gradle-path: 'android/app/build.gradle'
          version-code: 7
          version-name: '3.1.1'
          print-file: true
      - name: Commiting version change
        uses: zwaldowski/git-commit-action@v1
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: develop
```
